### ISSUE TITLE
FillStyle does not work with Chart.js 2.8.0

### ISSUE THREAD

**Issue by stockiNail** [nagix/chartjs-plugin-rough#1] opened 2019-03-18 17:47 UTC
I'm testing Rough plugin with CHART.JS 2.8.0 and I see that fillStyle does not work.

The legend is changing correctly but the fill of dataset not.

I'm using your sample [https://nagix.github.io/chartjs-plugin-rough/samples/interactions.html](https://nagix.github.io/chartjs-plugin-rough/samples/interactions.html) and changing only CHART.JS, you can see that it does not work.

```html
<head>
	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.bundle.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/rough.js/3.0.0/rough.js"></script>
	<script src="https://github.com/nagix/chartjs-plugin-rough/releases/download/v0.1.0/chartjs-plugin-rough.min.js"></script>
</head>
```

**Comment by nagix** [comment] 2019-03-26 07:22
Thanks for reporting this. I’m planning to release a new version that supports Chart.js 2.8 in a few days.

**Comment by nagix** [comment] 2019-03-29 10:01
@stockiNail What browser version are you using? This plugin fills arcs and line areas using SVG paths, and rough.js is using `2DPath` to draw them, but IE and Edge doesn't support it (see [this comment](https://github.com/pshihn/rough/issues/47#issuecomment-379643704)).

**Comment by stockiNail** [comment] 2019-03-29 10:25
@nagix tested it with FF 66.0.2 (64-bit) and Chrome Version 73.0.3683.86 (Official Build) (64-bit). No IE or Edge

**Comment by stockiNail** [comment] 2019-03-29 10:45
@nagix another topic (not related to this project). For my project, I have rewritten the "colorSchemes" public in JAVA, changing on my implementation some logic and features. Oki for you?

**Comment by nagix** [comment] 2019-03-29 12:07
@stockNail Hmm, did it work with Chart.js 2.7.3? I’m not able to reproduce the issue in my environment...

Regarding the colorschemes, feel free to modify and distribute it🙂

**Comment by stockiNail** [comment] 2019-03-29 12:28
@nagix  importing 2.7.3

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
```
it works. See here using  "cross-hatch" :

![cross-r](https://user-images.githubusercontent.com/11741250/55232404-c1c9b480-5225-11e9-9cef-fadd5ab34eb6.png)

importing 2.8.0

```html
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
```
it does not work. See here using  "cross-hatch" :

![cross-w](https://user-images.githubusercontent.com/11741250/55232423-d27a2a80-5225-11e9-92f4-72ef973f3f59.png)

It does not work also for other fillStyle. It seems it uses ONLY hachure.

Have a look the fillStyle is used into LEGEND.

**Comment by nagix** [comment] 2019-03-29 12:40
Ok, I understand the problem. It's already fixed in the master, and the fix will be included in the version 0.2.0 that will be released soon.

**Comment by stockiNail** [comment] 2019-03-29 13:17
Thank you very much.

I have seen that if you go to sample ["Interactions"](https://nagix.github.io/chartjs-plugin-rough/samples/interactions.html) and select "dots", it seems it's going in loop and the browser (FF 66.0.2 (64-bit)) shows the message to stop it.

![hangdots](https://user-images.githubusercontent.com/11741250/55235179-30f6d700-522d-11e9-96d7-ea39b875a29d.png)

**Comment by nagix** [comment] 2019-03-30 08:09
Rendering a SVG path shape in the `'dots'` fill style is very slow, and it seems that a browser is not able to respond due to many requests for animation in a rendering queue. I'm thinking of disabling animation when the `'dots'` fill style is selected.

**Comment by stockiNail** [comment] 2019-03-30 08:52
Sounds good. Hopefully the difference of rendering from 'dots' (disabling animation) and all other fill styles will not  be so visible to the user.

**Comment by nagix** [comment] 2019-03-31 09:04
The interaction sample was updated in 3a65a28. I didn't disable animations but set a lower limit of `hachureGap` based on `fillStyle` and the chart size. Try [this](https://nagix.github.io/chartjs-plugin-rough/samples/interactions.html) changing `fillStyle` and the window size.

**Comment by stockiNail** [comment] 2019-04-01 07:34
works perfectly! Thank you. I'm gonna included it in my project asap.

**Comment by stockiNail** [comment] 2019-04-01 11:04
I've checked in deep but the fix for dots  is apply only on the sample. Maybe it could be better to add directly into the plugin.

**Comment by stockiNail** [comment] 2019-04-01 11:41
In my opinion, we shouldn't force the user to add a specific code if we know that there is an issue without that code.

Therefore I would suggest to change `helpers.rough.js` the method `getFillOptions` as following;

```javascript
getFillOptions: function(options, canvas) {
	var values = {
		stroke: 'transparent',
		fill: options.backgroundColor
	};
	
	if (options.fillStyle === 'dots' || options.fillStyle === 'dashed' || options.fillStyle === 'zigzag-line') {
		hachureGapMin = Math.ceil(canvas.width * canvas.height / (options.fillStyle === 'dots' ? 20000 : 60000));
		options.hachureGap = Math.max(options.hachureGap, hachureGapMin);
	}

	this.roughKeys.forEach(function(key) {
		if (options[key] !== undefined) {
			values[key] = options[key];
		}
	});
	return values;
},
```

Accordingly we should also update the caller.

I'm not a javascript expert that's why I didn't create a PR

**Comment by nagix** [comment] 2019-04-01 12:54
The reason why I didn't change the plugin code was because the rendering performance varies by browsers, devices and platforms, so there is no reliable threshold for every use case. Also, rendering time changes depending on how many elements are on the chart, element types and the number of data points, so it should be decided by the application code.

I think it is a good idea to mention that this potentially causes a performance issue and how to workaround using `hachureGapMin` in the README.

**Comment by stockiNail** [comment] 2019-04-01 13:17
Understood. Let me say that from my experience who is using a component like a plugin does not want to take care about this kind of issues or special configurations. Nevertheless if there is not other option, I think it could be a good idea document it, as you wrote

**Closed as completed** 2019-04-03 10:21 UTC
